<a href="https://colab.research.google.com/github/StevenMena/05MIAR---Aprendizaje_Supervisado/blob/main/Programa5_SeleccionAtributos1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Selección de atributos no supervisada mediante eliminación por baja varianza.
import numpy as np
from sklearn.feature_selection import VarianceThreshold

In [4]:
# Carga de datos.
X = [[0, 0, 1], [0, 1, 0], [1, 0, 0],
     [0, 1, 1], [0, 1, 0], [0, 1, 1]]
print(np.shape(X))
print(np.array(X))

(6, 3)
[[0 0 1]
 [0 1 0]
 [1 0 0]
 [0 1 1]
 [0 1 0]
 [0 1 1]]


In [ ]:
# Limpieza de datos: selección de atributos.

# fijamos un umbral (th) para decidir qué porcentaje mínimo deben variar los valores de una columna para considerarse 
# una columna relevante a la hora de mantenerla en nuestro estudio
# El umbral utilizado en este ejemplo es 0,8, el cual deja pasar un atributo si varía al menos un 20 % a través de las instancias
# No se cumple ya que en este caso la columna 0 solo varia un 16%
th = 0.2
sel = VarianceThreshold(th)
print(sel.fit_transform(X))