In [1]:
import numpy as np
from sklearn.impute import SimpleImputer

In [2]:
# Carga de datos
X_train = [[1,      4], 
           [np.nan, 3], 
           [7,      8]]

In [3]:
# Limpieza de datos: imputación valores ausentes (modelo)
imputer = SimpleImputer(strategy='mean') # Utilizamos la estrategia de la media, pero también podemos ocupar la mediana y la moda

# Aplicar los métodos "fit" y "transform" para imputar los valores pérdidos de X_train
X_train_clean = imputer.fit_transform(X_train)
print(X_train_clean)
# el valor del nan ahora es 4, ya que como es la media, 7+1=8/2=4

[[1. 4.]
 [4. 3.]
 [7. 8.]]


In [5]:
# Imputación de valores ausentes sobre el conjunto de test
X_test = [[np.nan, 10], 
          [6,      np.nan], 
          [8,      2]]

# Imputar los datos del conjunto de test
#Aqui solo aplico el transform porque el imputador ya se establecio en el entrenamiento
#el imputador es independiente por columnas o atributos
X_test_clean = imputer.transform(X_test)

print(X_test_clean)
#porque toma 5 el valor del nan de la segunda columna??
#porque en los datos del entrenamiento la media de los 3 valores es 5, 4+3+8=15, 15/3=5
#esto de saber porque valor de sustituye es pregunta de examen

[[ 4. 10.]
 [ 6.  5.]
 [ 8.  2.]]


In [6]:
import pandas as pd

In [10]:
#Cargar dataframe

csv = pd.read_csv('penguins.csv',sep=';')
print(csv.head())



   CulmenLength  CulmenDepth  FlipperLength  BodyMass  Species
0          39.1         18.7          181.0    3750.0        0
1          39.5         17.4          186.0    3800.0        0
2          40.3         18.0          195.0    3250.0        0
3           NaN          NaN            NaN       NaN        0
4          36.7         19.3          193.0    3450.0        0


In [12]:
#paso mi data del csv al un ndarray de numpy
data = np.array(csv)
print(data)
#Compruebo que la fila 3 tiene valores nan
print(data[3])

[[3.910e+01 1.870e+01 1.810e+02 3.750e+03 0.000e+00]
 [3.950e+01 1.740e+01 1.860e+02 3.800e+03 0.000e+00]
 [4.030e+01 1.800e+01 1.950e+02 3.250e+03 0.000e+00]
 ...
 [4.960e+01 1.820e+01 1.930e+02 3.775e+03 2.000e+00]
 [5.080e+01 1.900e+01 2.100e+02 4.100e+03 2.000e+00]
 [5.020e+01 1.870e+01 1.980e+02 3.775e+03 2.000e+00]]
[nan nan nan nan  0.]


In [19]:
pos_ausentes = np.unique(np.where(np.isnan(data))[0])
print('Filas con valores ausentes: ', pos_ausentes)
display(pos_ausentes)

Filas con valores ausentes:  [  3 271]


array([  3, 271])

In [28]:
#Limpieza de datos: imputación valores ausentes (modelo)

imputer = SimpleImputer(strategy='mean')

data_clean = imputer.fit_transform(data)

print(data_clean)
print()
print(f"Fila #3 {data_clean[3]}")
print(f"Fila #271 {data_clean[271]}")

df = pd.DataFrame(data_clean, columns = ["Culmen length","Culmen depth","Flipper length","Body mass","Especies"])

display(df)

df.to_csv('penguins_clean.csv',sep=';')

[[3.910e+01 1.870e+01 1.810e+02 3.750e+03 0.000e+00]
 [3.950e+01 1.740e+01 1.860e+02 3.800e+03 0.000e+00]
 [4.030e+01 1.800e+01 1.950e+02 3.250e+03 0.000e+00]
 ...
 [4.960e+01 1.820e+01 1.930e+02 3.775e+03 2.000e+00]
 [5.080e+01 1.900e+01 2.100e+02 4.100e+03 2.000e+00]
 [5.020e+01 1.870e+01 1.980e+02 3.775e+03 2.000e+00]]

Fila #3 [  43.92192982   17.15116959  200.91520468 4201.75438596    0.        ]
Fila #271 [4.39219298e+01 1.71511696e+01 2.00915205e+02 4.20175439e+03
 1.00000000e+00]


Culmen length  Culmen depth  Flipper length    Body mass  Especies
0         39.10000      18.70000      181.000000  3750.000000       0.0
1         39.50000      17.40000      186.000000  3800.000000       0.0
2         40.30000      18.00000      195.000000  3250.000000       0.0
3         43.92193      17.15117      200.915205  4201.754386       0.0
4         36.70000      19.30000      193.000000  3450.000000       0.0
..             ...           ...             ...          ...       ...
339       55.80000      19.80000      207.000000  4000.000000       2.0
340       43.50000      18.10000      202.000000  3400.000000       2.0
341       49.60000      18.20000      193.000000  3775.000000       2.0
342       50.80000      19.00000      210.000000  4100.000000       2.0
343       50.20000      18.70000      198.000000  3775.000000       2.0

[344 rows x 5 columns]